### ISSUE TITLE
Change Logging trait to make _logger transient

### ISSUE THREAD

**Issue by deaktator** [eHarmony/aloha#157]
Change `Logging` trait to make `_logger` `@transient`.  This will limit the possibility of null pointer exceptions when deserializing models that extends `Logging`.

**Comment by deaktator** [comment]
Not sure if this is a deserialization issue or only happens when you deserialize and operate in multithreaded environments.  But it caused this issue that took a while to diagnose.

```
17/05/08 19:35:38 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerTaskEnd(8,0,ResultTask,ExceptionFailure(java.lang.NullPointerException,null,[Ljava.lang.StackTraceElement;@61d526b3,java.lang.NullPointerException
	at org.slf4j.impl.Log4jLoggerAdapter.isDebugEnabled(Log4jLoggerAdapter.java:200)
	at com.eharmony.aloha.util.Logger.isDebugEnabled(Logger.scala:45)
	at com.eharmony.aloha.util.Logger.debug(Logger.scala:54)
	at com.eharmony.aloha.util.Logging$class.debug(Logger.scala:215)
	at com.eharmony.aloha.models.reg.RegressionModel.debug(RegressionModel.scala:64)
	at com.eharmony.aloha.models.reg.RegressionModel.subvalue(RegressionModel.scala:94)
	at com.eharmony.aloha.models.tree.decision.ModelDecisionTree.processLeaf(ModelDecisionTree.scala:65)
	at com.eharmony.aloha.models.tree.decision.ModelDecisionTree$$anonfun$2.apply(ModelDecisionTree.scala:52)
	at com.eharmony.aloha.models.tree.decision.ModelDecisionTree$$anonfun$2.apply(ModelDecisionTree.scala:52)
	at scala.util.Either.fold(Either.scala:99)
	at com.eharmony.aloha.models.tree.decision.ModelDecisionTree.subvalue(ModelDecisionTree.scala:52)
	at com.eharmony.aloha.models.SubmodelBase$class.apply(SubmodelBase.scala:12)
	at com.eharmony.aloha.models.tree.decision.ModelDecisionTree.apply(ModelDecisionTree.scala:39)
	at com.zefr.dataScience.forecasting.evaluation.Main$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(Main.scala:50)
	at com.zefr.dataScience.forecasting.evaluation.Main$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(Main.scala:49)
	at scala.Option.flatMap(Option.scala:171)
	at com.zefr.dataScience.forecasting.evaluation.Main$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(Main.scala:49)
	at com.zefr.dataScience.forecasting.evaluation.Main$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(Main.scala:48)
	at scala.Option.flatMap(Option.scala:171)
	at com.zefr.dataScience.forecasting.evaluation.Main$$anonfun$1$$anonfun$apply$1.apply(Main.scala:48)
	at com.zefr.dataScience.forecasting.evaluation.Main$$anonfun$1$$anonfun$apply$1.apply(Main.scala:47)
	at scala.Option.flatMap(Option.scala:171)
	at com.zefr.dataScience.forecasting.evaluation.Main$$anonfun$1.apply(Main.scala:47)
	at com.zefr.dataScience.forecasting.evaluation.Main$$anonfun$1.apply(Main.scala:45)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:215)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:957)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:948)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:888)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:948)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:694)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
